BEGIN;

CREATE TABLE list_account (
    list_account_id BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT
    , list_id BIGINT UNSIGNED NOT NULL
    , account_id BIGINT UNSIGNED NOT NULL
    , created_on DATETIME NOT NULL
    , FOREIGN KEY (list_id) REFERENCES list(list_id) ON DELETE CASCADE
    , FOREIGN KEY (account_id) REFERENCES account(account_id) ON DELETE CASCADE
) ENGINE=InnoDB charset=utf8;

ALTER TABLE list ADD COLUMN account_id BIGINT UNSIGNED NOT NULL;
ALTER TABLE request ADD COLUMN account_id BIGINT UNSIGNED NOT NULL;
ALTER TABLE question ADD COLUMN account_id BIGINT UNSIGNED NOT NULL;

COMMIT;
